version: '3'

services:
    database:
        image: postgres:15-alpine
        environment:
            POSTGRES_PASSWORD: admin
            POSTGRES_USER: admin
        volumes:
            - database-volume:/var/lib/postgresql/data:rw
        ports:
            - 5432:5432

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
        ports:
            - 8080:80

    db:
        image: mariadb:11
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        volumes:
            - database-volume:/var/lib/mysql
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        ports:
            - 80:80

volumes:
    database-volume: {}
