version: '3'

services:
    database:
        image: postgres:${POSTGRES_VERSION:-15}-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
            POSTGRES_USER: ${POSTGRES_USER:-app}
        volumes:
            - database_data:/var/lib/postgresql/data:rw
            # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
            # - ./docker/db/data:/var/lib/postgresql/data:rw

    db:
        image: mysql:8.0.13
        container_name: db-mysql
        ports:
            - 3306
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=${PROJECT_NAME}
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin
        volumes:
            - database_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        container_name: phpmyadmin
        ports:
            - 80

    redis:
        image: redis:5-alpine
        ports:
            - 6379:6379

volumes:
    database_data: {}
