version: '3'

services:
    database:
        image: postgres:${POSTGRES_VERSION:-15}
        container_name: db-postgres
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
            POSTGRES_USER: ${POSTGRES_USER:-admin}
        volumes:
            - database_data:/var/lib/postgresql/data:rw
        ports:
            - ${POSTGRES_PORT:-5432}:5432

    pgadmin:
        image: dpage/pgadmin4:${PGADMIN_VERSION:-latest}
        container_name: pgadmin
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
        ports:
            - ${PGADMIN_PORT:-8080}:80

    db:
        image: mariadb:${MARIADB_VERSION:-11}
        container_name: db-mariadb
        restart: always
        environment:
            MYSQL_USER: ${MYSQL_USER:-admin}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-admin}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
        volumes:
            - database_data:/var/lib/mysql
        ports:
            - ${MYSQL_PORT:-3306}:3306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION:-latest}
        container_name: phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        ports:
            - ${PHPMYADMIN_PORT:-80}:80

    mongodb:
        image: mongo:${MONGODB_VERSION:-latest}
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-admin}
        volumes:
            - database_data:/data/db
        ports:
            - 27017:27017

volumes:
    database_data: {}
