version: '3'

services:
    db:
        image: mysql:8.0.13
        container_name: db-mysql
        ports:
            - 3306
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=${PROJECT_NAME}
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin
        volumes:
            - data-volume:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        container_name: phpmyadmin
        ports:
            - 80

    redis:
        image: redis:5-alpine
        ports:
            - 6379:6379

volumes:
    data-volume: {}
